name: Release
on:
  push:
    branches: [master]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files }}
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v2.3.1

      - name: Run npm ci
        id: npm_ci
        run: npm ci

      - name: Run gulp release
        id: gulp_release
        run: gulp release

      - name: Create Release
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path')

            const tagName = 'ReleaseDraft'
            const releaseName = 'Release Draft'
            const releaseMessage = `${fs.readFileSync('body').toString()}`;

            const scriptPath = path.resolve('./github.release.js')
            console.log(require(scriptPath)({context, github, tagName, releaseName, releaseMessage}, true))